#!/bin/bash -e

if VERSION=$(git describe --tags --match "release/*" --abbrev=0 2>/dev/null)
then
    # Use string operators to remove the release/ portion of version
    printf $(increment-version "${VERSION##*/}")
else  
    printf "1.0.0"
fi