#!/usr/bin/env python

import argparse

def increment_version(args):
    version = args.version
    numbers = version.split('.')
    print '.'.join([numbers[0], numbers[1], str(int(numbers[2]) + 1)])

parser = argparse.ArgumentParser(description='Increment patch version number of semantic version.')


parser.add_argument('version', type=str,
                          help='version to increment')
parser.set_defaults(func=increment_version)

args = parser.parse_args()
args.func(args)