#!/usr/bin/env python

import argparse
import sys

def increment_version(args):
    version = args.version
    numbers = version.split('.')
    sys.stdout.write('.'.join([numbers[0], numbers[1], str(int(numbers[2]) + 1)]))
    sys.stdout.flush()

parser = argparse.ArgumentParser(description='Increment patch version number of semantic version.')


parser.add_argument('version', type=str,
                          help='version to increment')
parser.set_defaults(func=increment_version)

args = parser.parse_args()
args.func(args)