#!/bin/bash

# Finds all docker image configuration files and pushes docker image changes
# to their corresponding docker repository.

find . -name "docker-image.cfg" | while read line; do
    (
        source "$line"
        
        IMAGE_DIRECTORY="$(dirname $line)"
        IMAGE_TAG="$IMAGE_NAME:latest"
        REPO_URL="$REPOSITORY_HOST/$IMAGE_TAG"

        eval "$( aws ecr get-login --no-include-email )"
        
        docker push "$REPO_URL"
    )
done