#!/bin/bash -xe

VERSION=$1

# Finds all docker image configuration files and pushes docker image changes
# to their corresponding docker repository.

find . -name "ecs.cfg" | while read line; do
    (
        # Get the ECS cluster and service configurations
        source "$line"
        IMAGE_DIRECTORY="$(dirname $line)"
        source "$IMAGE_DIRECTORY/docker-image.cfg"
        
        
        IMAGE_TAG="$IMAGE_NAME:$VERSION"
        REPO_URL_TAG="$REPOSITORY_HOST/$IMAGE_TAG"

        # Check if the latest version was tagged in the build process.
        # If so, deploy it.
        
        if docker image inspect "$REPO_URL_TAG" > /dev/null 2>&1
        then
            echo "Deploying $REPO_URL_TAG tag since a new version was detected"
            ecs deploy --tag "$VERSION" "$ECS_CLUSTER" "$ECS_SERVICE" 
        else
            echo "No new version detected for $IMAGE_NAME"
        fi
    )
done
